# Generated by Django 2.2.6 on 2020-01-03 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_feat_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='feat_artist',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='song',
            name='feat_songs',
        ),
        migrations.AddField(
            model_name='song',
            name='feat_songs',
            field=models.ManyToManyField(to='music.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feats', to=settings.AUTH_USER_MODEL),
        ),
    ]
