# Generated by Django 2.2.6 on 2020-01-04 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200104_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feat_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
